# Generated by Django 3.2.5 on 2021-11-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_auto_20211106_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
