# Generated by Django 3.2.9 on 2021-11-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0006_auto_20211107_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_type',
            field=models.CharField(choices=[('birthday', 'birthday'), ('aniversary', 'aniversary'), ('other', 'other')], max_length=20, null=True),
        ),
    ]
